### PR TITLE
Add -M option to run-bwamem

### PR DESCRIPTION
**Pull request by jpfeil**

### CODE REVIEW

**Comment by fnothaft** [comment]
+1, this would be really useful to have!

**Comment by jmarshall** [comment]
Isn't `-M` mostly for compatibility with a long-outdated version of Picard (cf #26)?  I'm curious why you're finding it useful.

**Comment by fnothaft** [comment]
@jmarshall I do believe that this is resolved on the updated version of Picard; if you want to close this, we can always reopen the PR if that is not the case.

**Comment by yfarjoun** [comment]
This has been resolved (in picard) for a very very long time. the only
thing that hasn't been resolved is the existence of the -M option in bwa...

**Comment by WortJohn** [comment]
"bwa mem -M" means the flag value which is 2048 is converted to 256. Firstly, you must understand the difference between supplementary alignment and secondary alignment. Officially, "**Typically, one
of the linear alignments in a chimeric alignment is considered the “representative” alignment, and the
others are called “supplementary” and are distinguished by the supplementary alignment flag.**" defines the supplementary alignment. And "**The correct placement of a read may be ambiguous, e.g. due to repeats. In this case, there may be multiple read alignments for the same read. One of these alignments is considered
primary. All the other alignments have the secondary alignment flag set in the SAM records that
represent them.**" defines the secondary alignment.

**Comment by jpfeil** [comment]
We were using the -M option for compatibility with Picard version 1.95.

**Pull request merged**
